# Generated by Django 3.0.5 on 2020-04-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MealTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_typ', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('serves', models.CharField(max_length=100)),
                ('prep_time_mins', models.FloatField()),
                ('prep_time_hours', models.FloatField()),
                ('cook_time_mins', models.FloatField()),
                ('cook_time_hours', models.FloatField()),
                ('method', models.TextField()),
                ('ingredients', models.TextField()),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Cuisine')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.MealTypes')),
            ],
        ),
    ]
