# Generated by Django 3.0.5 on 2020-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
