# Generated by Django 3.0.5 on 2020-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_word', models.CharField(max_length=100)),
                ('english_word', models.CharField(max_length=100)),
                ('vg_revision_list', models.BooleanField(default=False)),
                ('ben_revision_list', models.BooleanField(default=False)),
                ('olivia_revision_list', models.BooleanField(default=False)),
            ],
        ),
    ]
