# Generated by Django 3.0.5 on 2020-05-30 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spanish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='ben_revision_list',
        ),
        migrations.RemoveField(
            model_name='words',
            name='olivia_revision_list',
        ),
        migrations.RemoveField(
            model_name='words',
            name='vg_revision_list',
        ),
        migrations.AddField(
            model_name='words',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
