# Generated by Django 3.0.5 on 2020-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanish', '0002_auto_20200530_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='jg_list',
            field=models.BooleanField(default=False),
        ),
    ]
