# Generated by Django 3.0.5 on 2020-04-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20200422_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.Region'),
        ),
        migrations.DeleteModel(
            name='NewRegion',
        ),
    ]
