# Generated by Django 3.0.5 on 2020-04-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_auto_20200424_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wine.Country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wine.Region'),
        ),
    ]
