# Generated by Django 3.0.5 on 2020-04-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_auto_20200424_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('region',)},
        ),
    ]
