# Generated by Django 3.0.5 on 2020-04-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0006_auto_20200428_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
